#page title
page_title                                : HandsfreeLaptimer                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6751469529                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : de                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : HandsfreeLaptimer - FPVTracker            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track your laptimes by voice commands.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mats Wiese                               
your_link                                 :                  
your_city                                 :                                
email_address                             : handsfreelaptimer@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : matswiese
youtube_username                          : stammix
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Race your Drone
    description                           : Fly the track you like!
    fontawesome_icon_name                 : arrows-spin
    
  - title                                 : Controlled by voice
    description                           : When you can't use your hands, use your voice!
    fontawesome_icon_name                 : microphone-lines

  - title                                 : Easy and quick setup
    description                           : No need for a complicated setup. Just start the app and start racing.
    fontawesome_icon_name                 : truck-fast   

  - title                                 : Get acoustic feedback
    description                           : When your eyes are covert by your goggles, you get confirmation.
    fontawesome_icon_name                 : ear-listen
    
  - title                                 : Customizable
    description                           : You can change the sounds and even the words to command the app. 
    fontawesome_icon_name                 : gears

  - title                                 : Track history
    description                           : See all laps of the challenge as an overview.
    fontawesome_icon_name                 : clipboard-list
    
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage2.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                      # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#00ffff"

app_title_color                           : "#00ffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#00ffff"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#00ffff" 
feature_icons_background_color            : "#666666"

social_icons_foreground_color             : "#00ff66" # "#666666"
social_icons_background_color             : "#003cff" # "#e6e6e6"

footer_text_color                         : "#00ffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
